---
title: "null"
author: "null"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
favicon: images/favicon.ico
---
# 20210 and 2020 Comparison {-}
## Dallas County Census Tract Map {-}

```{r, include=FALSE, echo=FALSE, warning=FALSE}
###############################################################################################
theme_cpal <- function(base_size = 12, base_family = "sans") {
  colors <- deframe(ggthemes::ggthemes_data[["fivethirtyeight"]])
  (theme_foundation(base_size = base_size, base_family = base_family)
    + theme(
      line = element_line(colour = "#b4b4b4"),
      rect = element_rect(fill = "#ffffff",
                          linetype = 1, colour = NA),
      text = element_text(family = "Roboto", face = "bold", colour = "#6c6c6c"),
      axis.title = element_text(),
      axis.title.x = element_text(vjust = 2),
      axis.title.y = element_text(vjust = 2),
      axis.text = element_text(color = "#b4b4b4"),
      axis.ticks = element_blank(),
      #axis.ticks.length = unit(6, "pt"),
      axis.line = element_line(color = "#b4b4b4", size = 1.5, linetype = "solid"),
      legend.background = element_rect(),
      legend.position = "none",
      legend.direction = "horizontal",
      legend.box = "horizontal",
      panel.grid.major = element_line(colour = "#e1e1e1"),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0, size = rel(1.5), face = "bold"),
      plot.margin = unit(c(1, 3, 1, 1), "lines"),
      panel.border = element_rect(size=1, fill = NA),
      strip.background = element_rect()
    ))
}
CPAL.colors = c("#008097", "#ec008c", "#eaca2d", "#b4b4b4", "#9bd9e3", "#fdddd7", "#55107E")
CPAL.colors.Rev = c("#fdddd7", "#9bd9e3", "#b4b4b4", "#eaca2d", "#ec008c", "#008097")
CPAL.colors.Rev.Lim = c("#eaca2d", "#ec008c", "#008097")
###############################################################################################
library(tidyverse)
library(tidycensus)
library(tigris)
library(rio)
library(ggthemes)
library(leaflet)
library(sf)
library(plotly)
library(knitr)
library(kableExtra)
library(htmltools)
###############################################################################################
tract2010 <- tracts(state = "TX") %>%
  filter(COUNTYFP %in% c("085", "113", "439", "121"))
tract2020 <- tracts(state = "TX", cb = TRUE, year = 2020) %>%
  filter(COUNTYFP %in% c("085", "113", "439", "121"))
county <- counties(state = "TX") %>%
  filter(NAME %in% c("Dallas", "Collin", "Tarrant", "Denton"))
```

Comparison of 2010 Census Tract boundaries for North Texas 4County and 2020 Census Tract boundaries.
```{r, fig.height=8, fig.width=8, echo=FALSE, message=FALSE, warning=FALSE}
#mapbox <- "https://api.mapbox.com/styles/v1/owencpal/ckecb71jp22ct19qc1id28jku/tiles/256/%7Bz%7D/%7Bx%7D/%7By%7D@2x?access_token=pk.eyJ1Ijoib3dlbmNwYWwiLCJhIjoiY2tlYnR3emdxMGNhZzMwb2EzZWR4ajloNCJ9.P7Mujz8F3Rssq5-Q6dcvMw.png"
leaflet() %>%
  setView(lng = -97.026, lat = 32.918, zoom = 9) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = tract2020,
              stroke = TRUE,
              weight = 2,
              opacity = 1,
              smoothFactor = 0.2,
              fillOpacity = 0,
              color = "#000000",
              group = "2020 Tracts",
              popup = ~htmlEscape(NAMELSAD)) %>%
  addPolygons(data = tract2010, 
              stroke = TRUE,
              weight = 2,
              opacity = 1,
              smoothFactor = 0.2,
              fillOpacity = 0,
              color = "#ec008c",
              group = "2010 Tracts",
              popup = ~htmlEscape(NAMELSAD)) %>%
  addPolygons(data = county,
              stroke = TRUE,
              weight = 6,
              opacity = 1,
              color = "#000000",
              fillOpacity = 0,
              group = "County") %>%
  addLayersControl(baseGroups = "County",
                   overlayGroups = c("2010 Tracts", "2020 Tracts"),
                   options = layersControlOptions(collapsed = FALSE))
```